# Generated by Django 3.2.22 on 2023-11-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
