# Generated by Django 3.2.22 on 2023-11-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
